from django.urls import path
from .views import (
    AuthLoginView,
    AuthMeView,
    AuthLogoutView,
    health,
    CatalogoView,
    PedidoCreateView,
    PedidoDetailView,
    PedidoHistorialView,
    PedidoCambiarEstadoView,
    PedidoConfirmarInsumosView,
    PedidoRequerimientosView,
    TicketByFolioView,
    ProduccionTableroView,
    MesaLiberarView,
    InventarioIngredientesView,
    InventarioEntradaView,
    InventarioMovimientosView,
    ReporteTopProductosView,
    AdminDashboardView,
    AdminAccionesListView,
    AdminAccionDeshacerView,
    AdminProductoListCreateView,
    AdminProductoDetailView,
    AdminIngredienteListCreateView,
    AdminIngredienteDetailView,
    AdminMesaListCreateView,
    AdminMesaDetailView,
)

urlpatterns = [
    path('auth/login/', AuthLoginView.as_view()),
    path('auth/me/', AuthMeView.as_view()),
    path('auth/logout/', AuthLogoutView.as_view()),
    path('health/', health),
    path('catalogo/', CatalogoView.as_view()),
    path('pedidos/', PedidoCreateView.as_view()),
    path('pedidos/historial/', PedidoHistorialView.as_view()),
    path('pedidos/<int:pedido_id>/', PedidoDetailView.as_view()),
    path('pedidos/<int:pedido_id>/estado/', PedidoCambiarEstadoView.as_view()),
    path('pedidos/<int:pedido_id>/confirmar-insumos/', PedidoConfirmarInsumosView.as_view()),
    path('pedidos/<int:pedido_id>/requerimientos/', PedidoRequerimientosView.as_view()),
    path('tickets/<str:folio>/', TicketByFolioView.as_view()),
    path('produccion/tablero/', ProduccionTableroView.as_view()),
    path('mesas/<int:mesa_id>/liberar/', MesaLiberarView.as_view()),
    path('inventario/ingredientes/', InventarioIngredientesView.as_view()),
    path('inventario/entradas/', InventarioEntradaView.as_view()),
    path('inventario/movimientos/', InventarioMovimientosView.as_view()),
    path('reportes/top-productos/', ReporteTopProductosView.as_view()),
    path('admin/dashboard/', AdminDashboardView.as_view()),
    path('admin/acciones/', AdminAccionesListView.as_view()),
    path('admin/acciones/<int:accion_id>/deshacer/', AdminAccionDeshacerView.as_view()),
    path('admin/productos/', AdminProductoListCreateView.as_view()),
    path('admin/productos/<int:producto_id>/', AdminProductoDetailView.as_view()),
    path('admin/ingredientes/', AdminIngredienteListCreateView.as_view()),
    path('admin/ingredientes/<int:ingrediente_id>/', AdminIngredienteDetailView.as_view()),
    path('admin/mesas/', AdminMesaListCreateView.as_view()),
    path('admin/mesas/<int:mesa_id>/', AdminMesaDetailView.as_view()),
]
