# Generated by Django 5.2.7 on 2026-03-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='rol',
            field=models.CharField(choices=[('produccion', 'Produccion'), ('admin', 'Admin')], default='produccion', max_length=20),
        ),
    ]
