# Generated by Django 5.2.7 on 2026-03-22 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_usuarioperfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('producto', 'Producto'), ('ingrediente', 'Ingrediente'), ('mesa', 'Mesa'), ('inventario_entrada', 'Entrada Inventario')], max_length=40)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar')], max_length=20)),
                ('entidad_id', models.PositiveIntegerField(blank=True, null=True)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('despues', models.JSONField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('deshecha', models.BooleanField(default=False)),
                ('deshecha_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
